import type { SpeakerEvent, SpeakerLog } from './types';

/**
 * All chrome.runtime.sendMessage type constants.
 * ALWAYS use these — never raw strings in sendMessage calls.
 */
export const MSG = {
  // popup → background
  RECORDING_START:   'RECORDING_START',
  RECORDING_STOP:    'RECORDING_STOP',
  // background → offscreen
  START_OFFSCREEN:   'START_OFFSCREEN',
  STOP_OFFSCREEN:    'STOP_OFFSCREEN',
  // background → content
  RECORDING_STARTED: 'RECORDING_STARTED',
  RECORDING_STOPPED: 'RECORDING_STOPPED',
  // offscreen → background
  AUDIO_BLOB_READY:  'AUDIO_BLOB_READY',
  // content → background
  SPEAKER_LOG_READY: 'SPEAKER_LOG_READY',
  MEETING_ENDED:     'MEETING_ENDED',
  // offscreen → background → content (mic audio level for self-speaking detection)
  MIC_ACTIVITY:      'MIC_ACTIVITY',
  // offscreen → background → content (tab audio level for remote-speaking detection)
  TAB_ACTIVITY:      'TAB_ACTIVITY',
  // offscreen → background (diagnostics)
  OFFSCREEN_LOG:     'OFFSCREEN_LOG',

  // ── Streaming backend (Phase 0+) ─────────────────────────────────────────
  /** content → background → offscreen+sidepanel: speaker segment start/end */
  SPEAKER_EVENT:     'SPEAKER_EVENT',
  /** offscreen → background: POST /sessions succeeded, persist sessionId */
  SESSION_CREATED:   'SESSION_CREATED',
  /** offscreen → background: uploader drained and /complete called, safe to close */
  OFFSCREEN_DONE:    'OFFSCREEN_DONE',
  /** offscreen → background → sidepanel: IDB quota approaching limit */
  STORAGE_WARNING:   'STORAGE_WARNING',
} as const;

export type MsgType = typeof MSG[keyof typeof MSG];

/** Base message shape */
export interface BaseMessage {
  type: MsgType;
}

/** offscreen → background: audio capture complete */
export interface AudioBlobReadyMessage extends BaseMessage {
  type: typeof MSG.AUDIO_BLOB_READY;
  payload: {
    audioBase64: string;
    audioMimeType: string;
    recordingStartMs: number;
  };
}

/** content → background: speaker log flushed */
export interface SpeakerLogReadyMessage extends BaseMessage {
  type: typeof MSG.SPEAKER_LOG_READY;
  payload: { log: SpeakerLog };
}

/** background → offscreen: start capturing tab audio */
export interface StartOffscreenMessage extends BaseMessage {
  type: typeof MSG.START_OFFSCREEN;
  payload: {
    streamId: string;
    /** Single clock anchor generated by background before broadcast. */
    recordingStartMs: number;
    /** Client-generated session UUID (used also by offscreen when POST /sessions). */
    sessionId: string;
    platform: 'meet' | 'telemost';
    meetingId?: string;
  };
}

/** background → content: speaker tracker should start; carries shared clock + session */
export interface RecordingStartedMessage extends BaseMessage {
  type: typeof MSG.RECORDING_STARTED;
  payload: {
    recordingStartMs: number;
    sessionId: string;
  };
}

// ── Streaming backend messages ─────────────────────────────────────────────

/** content → background → offscreen+sidepanel: one speaker boundary event */
export interface SpeakerEventMessage extends BaseMessage {
  type: typeof MSG.SPEAKER_EVENT;
  payload: { event: SpeakerEvent; sessionId: string };
}

/** offscreen → background: POST /sessions succeeded on backend */
export interface SessionCreatedMessage extends BaseMessage {
  type: typeof MSG.SESSION_CREATED;
  payload: { sessionId: string };
}

/** offscreen → background: drain + /complete finished, safe to close offscreen */
export interface OffscreenDoneMessage extends BaseMessage {
  type: typeof MSG.OFFSCREEN_DONE;
  payload: {
    sessionId: string | null;
    expectedChunks: number;
    /** If true, some chunks remain unsent (backend was unreachable at stop). */
    partial: boolean;
  };
}

/** offscreen → background → sidepanel: IDB is filling up */
export interface StorageWarningMessage extends BaseMessage {
  type: typeof MSG.STORAGE_WARNING;
  payload: {
    /** usage / quota ratio, 0..1 */
    ratio: number;
    /** If true, new chunks are being dropped (ratio > 0.95). */
    dropping: boolean;
  };
}
